// import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
// import { extractRouterConfig } from "uploadthing/server";
// import "@uploadthing/react/styles.css";
// import { ourFileRouter } from "./api/uploadimage/core";
 

import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {/* <NextSSRPlugin */}
          {/* /**
           * The `extractRouterConfig` will extract **only** the route configs
           * from the router to prevent additional information from being
           * leaked to the client. The data passed to the client is the same
           * as if you were to fetch `/api/uploadthing` directly.
           */ }
         {/* routerConfig={extractRouterConfig(ourFileRouter)} */}
        {/* /> */}
        {children}
        </body>
    </html>
  );
}
